

services:
  postgresql:
    image: postgres
    container_name: todolist
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=todolist
      - POSTGRES_PASSWORD=todolist
      - POSTGRES_DATABASE=todolist
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-todolist
    ports:
      - '6379:6379'
